"""Add imageKey and imageURL to ClothesEntity

Revision ID: 52d211949bb5
Revises: b7c9d8e1f2a3
Create Date: 2026-05-06 20:53:42.243163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52d211949bb5'
down_revision: Union[str, Sequence[str], None] = 'b7c9d8e1f2a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clothes', sa.Column('imageKey', sa.String(), nullable=True))
    op.add_column('clothes', sa.Column('imageURL', sa.String(), nullable=True))
    op.alter_column('clothes', 'userId',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index('ix_clothes_userId', table_name='clothes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_clothes_userId', 'clothes', ['userId'], unique=False)
    op.alter_column('clothes', 'userId',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('clothes', 'imageURL')
    op.drop_column('clothes', 'imageKey')
    # ### end Alembic commands ###
