"""mapped columns to everything

Revision ID: dcfe0791c9f0
Revises: 081df979b0fa
Create Date: 2026-04-30 12:27:00.511427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dcfe0791c9f0'
down_revision: Union[str, Sequence[str], None] = '081df979b0fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fits', 'createdAt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('user_clothes', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_clothes', 'addedAt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('users', 'createdAt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'createdAt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('user_clothes', 'addedAt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('user_clothes', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('fits', 'createdAt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###
