"""Remove imageURL from clothes table

Revision ID: f07db45a90d1
Revises: 52d211949bb5
Create Date: 2026-05-06 23:20:32.643612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f07db45a90d1'
down_revision: Union[str, Sequence[str], None] = '52d211949bb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clothes', 'imageURL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clothes', sa.Column('imageURL', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
